repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: rubocop
        name: rubocop
        entry: rubocop --auto-correct
        types: [ruby]
        language: ruby
        additional_dependencies: ['rubocop:0.63.1']
