Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30
Metrics/LineLength:
  IgnoreCopDirectives: true
Style/Documentation:
  Enabled: false
