resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: asottile-github
      name: asottile/azure-pipeline-templates
      ref: refs/heads/pre-commit

jobs:
- template: job--pre-commit.yml@asottile
